name: Publish to PyPI (Trusted Publishing)

on:
  push:
    tags:
      - "v1.0"           # e.g. v0.1.0

permissions:
  contents: read
  id-token: write      # REQUIRED for Trusted Publishing (OIDC)

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    # Optional: require an environment to gate releases
    environment: pypi

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build

      - name: Build sdist and wheel
        run: python -m build

      # No username/password: OIDC will be used
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # If you configured an environment named "pypi", this job
          # will inherit its protection rules (e.g. required review).
          # No extra inputs needed for PyPI. For TestPyPI, see variant below.
          verbose: true
